language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
before_script:
  - psql -c "CREATE USER jiweiweisg WITH PASSWORD 'jiweiweisg';" -U postgres
  - psql -c 'create database sg_property_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake --trace db:test:prepare